questions = [
    {
        "Nº": 1,
        "Dificuldade": "Médio",
        "Questao": "Qual é a receita líquida da empresa?",
        "Onde": ["2.1"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Localize o valor da 'Receita de vendas de bens e serviços' ou, em caso de bancos, 'Receitas da Intermediação Financeira'.",
        "RegrasDeFormatacao": "A resposta deve ser um número. Se o valor estiver em milhares (R$ mil), multiplique por 1.000 (adicione '000' ao final).",
    },
    {
        "Nº": 2,
        "Dificuldade": "Médio",
        "Questao": "Qual é o lucro líquido da empresa?",
        "Onde": ["2.1"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Localize o valor do 'Lucro Líquido'.",
        "RegrasDeFormatacao": "A resposta deve ser um número. Se for prejuízo, o número deve ser negativo. Se o valor estiver em milhares (R$ mil), multiplique por 1.000.",
    },
    {
        "Nº": 3,
        "Dificuldade": "Fácil",
        "Questao": "Qual é a firma de auditoria independente?",
        "Onde": ["9.1"],
        "TipoDeResposta": "ExtracaoTexto",
        "CriteriosDeAnalise": "Identifique o nome (Razão Social) da empresa de auditoria independente referente ao último ano.",
        "RegrasDeFormatacao": "Abrevie os nomes da seguinte forma: 'DELOITTE' para 'DTT', 'ERNST & YOUNG' para 'EY'. Outras como KPMG e PWC não precisam de abreviação.",
    },
    {
        "Nº": 4,
        "Dificuldade": "Difícil",
        "Questao": "Qual o valor dos gastos anuais com a empresa de auditoria independente?",
        "Onde": ["9.1"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Localize o 'Montante total da remuneração dos auditores independentes segregado por serviço' do último ano. Some todos os valores relacionados à auditoria, incluindo 'carta conforto', se houver.",
        "RegrasDeFormatacao": "A resposta deve ser um número. Se o valor estiver em milhares (R$ mil), multiplique por 1.000.",
    },
    {
        "Nº": 5,
        "Dificuldade": "Difícil",
        "Questao": "Qual o valor dos eventuais gastos com serviços adicionais prestados pela firma de auditoria independente?",
        "Onde": ["9.1"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Calcule a soma dos gastos referentes aos serviços não associados à auditoria externa (auditoria).",
        "RegrasDeFormatacao": "A resposta deve ser um número. Se o valor estiver em milhares (R$ mil), multiplique por 1.000.",
    },
    {
        "Nº": 6,
        "Dificuldade": "Médio",
        "Questao": "A companhia possui uma política de gerenciamento de riscos?",
        "Onde": ["5.1"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Sim' se a empresa afirmar que possui uma política de gerenciamento de riscos (mesmo que sejam várias políticas, como de crédito, cambial, etc.). Use 'Não' se a empresa informar que não tem tal política. Use 'Não Divulgado' se a informação não estiver presente.",
        "OpcoesDeResposta": ["Sim", "Não", "Não Divulgado"],
    },
    {
        "Nº": 7,
        "Dificuldade": "Fácil",
        "Questao": "A empresa divulga a existência de auditoria interna?",
        "Onde": ["5.2"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Sim' se o texto mencionar a existência de uma área ou função de auditoria interna. Use 'Não' caso o texto negue a existência ou seja omisso.",
        "OpcoesDeResposta": ["Sim", "Não"],
    },
    {
        "Nº": 8,
        "Dificuldade": "Médio",
        "Questao": "O sistema de controles internos da companhia está adequado?",
        "Onde": ["5.2"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Sim' se a empresa citar ter uma estrutura de controles internos adequada. Use 'Não' se afirmar categoricamente que o sistema NÃO está adequado. Use 'Não Aplicado' se não existir sistema de controle. Use 'Não Divulgado' se a informação não for fornecida.",
        "OpcoesDeResposta": ["Sim", "Não", "Não Divulgado", "Não Aplicado"],
    },
    {
        "Nº": 9,
        "Dificuldade": "Médio",
        "Questao": "Houve deficiências ou recomendações significativas sobre os controles internos apresentadas pelo auditor independente?",
        "Onde": ["5.2"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Sim' se o texto mencionar a existência de deficiências ou recomendações pelo auditor. Use 'Não' se o texto afirmar que não houve deficiências ou recomendações. Use 'Não Divulgado' se a informação não estiver presente.",
        "OpcoesDeResposta": ["Sim", "Não", "Não Divulgado"],
    },
    {
        "Nº": 10,
        "Dificuldade": "Fácil",
        "Questao": "O emissor divulga informações sociais e ambientais e de governança corporativa (ASG)?",
        "Onde": ["1.9"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Sim' se a empresa citar que divulga Relatório Anual Integrado, Relatório de Sustentabilidade ou documento similar. Use 'Não' se a empresa não mencionar a divulgação de tais informações.",
        "OpcoesDeResposta": ["Sim", "Não", "Não Aplicado"],
    },
    {
        "Nº": 11,
        "Dificuldade": "Fácil",
        "Questao": "O Conselho Fiscal está instalado?",
        "Onde": ["7.1", "7.3"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Sim' se a empresa afirmar que o Conselho Fiscal está atualmente instalado. Use 'Não' se afirmar que não está instalado. Use 'Não Divulgado' se a informação não for fornecida.",
        "OpcoesDeResposta": ["Sim", "Não", "Não Divulgado"],
    },
    {
        "Nº": 12,
        "Dificuldade": "Difícil",
        "Questao": "Quantos Comitês do Conselho de Administração?",
        "Onde": ["7.2", "7.4"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Conte o número de Comitês de Assessoramento ao Conselho de Administração.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 13,
        "Dificuldade": "Difícil",
        "Questao": "A companhia possui regras específicas de identificação e administração de conflitos de interesses?",
        "Onde": ["7.1", "11.1"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Verifique se a empresa menciona possuir 'Regras sobre conflitos de interesses' OU uma 'Política de transação com partes relacionadas'. Se encontrar qualquer uma das duas, classifique como 'Sim'. Caso contrário, 'Não'.",
        "OpcoesDeResposta": ["Sim", "Não"],
    },
    {
        "Nº": 14,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros compõem o Conselho de Administração?",
        "Onde": ["7.3", "7.1"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Conte a quantidade de Conselheiros de Administração efetivos, incluindo Presidente e Vice-Presidente. Não conte suplentes.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 15,
        "Dificuldade": "Médio",
        "Questao": "Quantas mulheres no Conselho de Administração?",
        "Onde": ["7.3", "7.1"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Conte a quantidade de mulheres no Conselho de Administração.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 16,
        "Dificuldade": "Médio",
        "Questao": "Quantos conselheiros são externos?",
        "Onde": ["7.3"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Conte a quantidade de conselheiros que não atuam como Diretores (executivos) da companhia e não são classificados como Independentes.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 17,
        "Dificuldade": "Médio",
        "Questao": "Quantos conselheiros são independentes?",
        "Onde": ["7.3", "7.1"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Conte a quantidade de membros classificados como 'Conselheiro Independente'.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 18,
        "Dificuldade": "Médio",
        "Questao": "Quantos conselheiros são executivos da Empresa?",
        "Onde": ["7.3"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Conte a quantidade de conselheiros que também são Diretores na empresa.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 19,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros compõem o Comitê de Auditoria?",
        "Onde": ["7.4"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Conte a quantidade total de membros do Comitê de Auditoria.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 20,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros do Comitê de Auditoria são conselheiros?",
        "Onde": ["7.4", "7.3"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Identifique os membros do Comitê de Auditoria e verifique quantos deles também são membros do Conselho de Administração.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 21,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros do Comitê de Auditoria são conselheiros independentes?",
        "Onde": ["7.4", "7.3"],
        "TipoDeResposta": "ExtracaoNumerica",
        "CriteriosDeAnalise": "Identifique os membros do Comitê de Auditoria e verifique quantos deles são classificados como conselheiros independentes.",
        "RegrasDeFormatacao": "A resposta deve ser um número inteiro.",
    },
    {
        "Nº": 22,
        "Dificuldade": "Médio",
        "Questao": "O Comitê de Auditoria é coordenado por um conselheiro independente?",
        "Onde": ["7.4", "7.3"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Verifique se o Coordenador do Comitê de Auditoria é classificado como um conselheiro independente. Se for, a resposta é 'Sim', caso contrário é 'Não'.",
        "OpcoesDeResposta": ["Sim", "Não"],
    },
    {
        "Nº": 23,
        "Dificuldade": "Fácil",
        "Questao": "A empresa contrata seguro D&O para seus conselheiros e diretores, ou prevê outra forma de reembolso de despesas?",
        "Onde": ["7.7"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Seguro D&O' se o texto afirma que a empresa possui seguro D&O ou 'Seguro de Responsabilidade Civil'. Use 'Outra forma de reembolso' se afirma possuir outra forma de reembolso que não seja o D&O. Use 'Não' se nega explicitamente possuir qualquer seguro ou reembolso. Use 'Não Divulgado' se a informação não estiver disponível.",
        "OpcoesDeResposta": [
            "Seguro D&O",
            "Outra forma de reembolso",
            "Não",
            "Não Divulgado",
        ],
    },
    {
        "Nº": 24,
        "Dificuldade": "Médio",
        "Questao": "O emissor identificou casos de desvios, fraudes, irregularidades e atos ilícitos praticados contra a administração pública?",
        "Onde": ["5.3"],
        "TipoDeResposta": "Classificacao",
        "CriteriosDeAnalise": "Use 'Sim' se o texto afirmar que a empresa identificou casos de desvios, fraudes, irregularidades ou atos ilícitos contra a administração pública nos últimos 3 exercícios sociais. Use 'Não' se o texto afirmar explicitamente que a empresa NÃO identificou tais casos no mesmo período. Use 'Não Divulgado' se o texto for omisso sobre o assunto. Dica: A informação pode estar relacionada à menção de risco de fraude no item 4.1.",
        "OpcoesDeResposta": ["Sim", "Não", "Não Divulgado"],
    },
]
