questions = [
    {
        "Nº": 1,
        "Dificuldade": "Médio",
        "Questao": "Qual é a receita líquida da empresa?",
        "Onde": ["2.1"],
        "ComoPreencher": 'COPIAR "Receita de vendas de bens e serviços"\nAtentar-se para a necessidade de multiplicar por mil ou milhão\nTambém pode ser obtido nas DFs',
        "OBSERVACOES": 'Campo Aberto - Observar se o número está em RS (mil), em caso positivo incluir 000 no final. (Em Bancos estará nomeado como "Receitas da Intermediação Financeira")',
    },
    {
        "Nº": 2,
        "Dificuldade": "Médio",
        "Questao": "Qual é o lucro líquido da empresa?",
        "Onde": ["2.1"],
        "ComoPreencher": 'COPIAR o valor do "Lucro Líquido". Atentar-se para o prejuizo, se prejuizo incluir "-".\nTambém pode ser obtido nas DFs',
        "OBSERVACOES": "Campo aberto, preencher com número. Caso esteja em RS (mil), incluir 000 no final.",
    },
    {
        "Nº": 3,
        "Dificuldade": "Fácil",
        "Questao": "Qual é a firma de auditoria independente?",
        "Onde": ["9.1"],
        "ComoPreencher": "Coletar o nome da firma de auditoria independente do ultimo ano.\nSe Deloitte ou Ernest, abreviar conforme ao lado.",
        "OBSERVACOES": "DELOITTE = DTT \nERNEST E YOUNG = EY\nKPMG\nPWC",
    },
    {
        "Nº": 4,
        "Dificuldade": "Difícil",
        "Questao": "Qual o valor dos gastos anuais com a empresa de auditoria independente?",
        "Onde": ["9.1"],
        "ComoPreencher": "COPIAR e COLAR > “Montante total da remuneração dos auditores independentes segregado por serviço”. Considerar último ano. (ADICIONAR CARTA CONFORTO)",
        "OBSERVACOES": "Campo Aberto - Somar os gastos caso a firma preste outros serviços.",
    },
    {
        "Nº": 5,
        "Dificuldade": "Difícil",
        "Questao": "Qual o valor dos eventuais gastos com serviços adicionais prestados pela firma de auditoria independente?",
        "Onde": ["9.1"],
        "ComoPreencher": "CALCULAR o montante dos gastos referentes aos serviços não associados à AUDITORIA (externa).",
        "OBSERVACOES": "Campo Aberto - Atentar-se ao (R$ mil)",
    },
    {
        "Nº": 6,
        "Dificuldade": "Médio",
        "Questao": "A companhia possui uma política de gerenciamento de riscos?",
        "Onde": ["5.1"],
        "ComoPreencher": "SIM - Caso a empresa não tenha uma política de gerenciamento de riscos única, mas sim várias políticas (Política de Risco de Crédito, Política de Risco Cambial, etc) buscar a de riscos estratégicos ou risco de estratégia.\nNÃO - Se a empresa informa que não tem política de gerenciamento de riscos\nNÃO DIVULGADO - A empresa não disponibilizou essa informação",
        "OBSERVACOES": "Opções - Sim, Não ou Não Divulgado",
    },
    {
        "Nº": 7,
        "Dificuldade": "Fácil",
        "Questao": "A empresa divulga a existência de auditoria interna?",
        "Onde": ["5.2"],
        "ComoPreencher": "SIM = A empresa divulga a existência de auditoria interna\nNÃO = A empresa não divulga se tem auditoria interna",
        "OBSERVACOES": "Opções - Sim, Não",
    },
    {
        "Nº": 8,
        "Dificuldade": "Médio",
        "Questao": "O sistema de controles internos da companhia está adequado?",
        "Onde": ["5.2"],
        "ComoPreencher": "SIM = A empresa cita ter uma estrutura de controles internos adequada.\nNÃO = A empresa afirma categoricamente que o sistema de controles NÃO está adequado\nNão Divulgado = A empreas não disponibiliza a informação\nNão Aplicado = Não existe sistema de controle na empresa",
        "OBSERVACOES": "Opções - Sim, Não, Não Divulgado e Não Aplicado",
    },
    {
        "Nº": 9,
        "Dificuldade": "Médio",
        "Questao": "Houve deficiências ou recomendações significativas sobre os controles internos apresentadas pelo auditor independente?",
        "Onde": ["5.2"],
        "ComoPreencher": "SIM = HOUVE deficiências OU recomendações.\nNÃO = Sem deficiências ou recomendações\nNÃO DIVULGADO = A empresa não disponibilizou essa informação",
        "OBSERVACOES": "Opções - Sim, Não e Não Divulgado",
    },
    {
        "Nº": 10,
        "Dificuldade": "Fácil",
        "Questao": "O emissor divulga informações sociais e ambientais e de governança corporativa (ASG)?",
        "Onde": ["1.9"],
        "ComoPreencher": "SIM= a empresa cita que divulga o Relatório Anual Integrado, o Relatório de Sustentabilidade ou algum outro documento do tipo\nNÃO = a empresa não divulga informações sociais e ambientais",
        "OBSERVACOES": "Opções - Sim, Não e Não Aplicado",
    },
    {
        "Nº": 11,
        "Dificuldade": "Fácil",
        "Questao": "O Conselho Fiscal está instalado?",
        "Onde": ["7.1", "7.3"],
        "ComoPreencher": "SIM = A empresa afirma que o Conselho Fiscal está instalado (Hoje).\nNÃO = A empresa afirma que o Conselho Fiscal NÃO está instalado\nNÃO DIVULGADO = Informação não disponibilizada",
        "OBSERVACOES": "Opções - Sim, Não, Não Divulgado",
    },
    {
        "Nº": 12,
        "Dificuldade": "Difícil",
        "Questao": "Quantos Comitês do Conselho de Administração?",
        "Onde": ["7.2", "7.4"],
        "ComoPreencher": "CONTAR o número de Comitês do Conselho de Administração.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 13,
        "Dificuldade": "Difícil",
        "Questao": "A companhia possui regras específicas de identificação e administração de conflitos de interesses?",
        "Onde": ["7.1", "11.1"],
        "ComoPreencher": "Há duas possibilidade de resposta: Regras sobre conflitos de interesses OU Política de transação com partes relacionadas. Devemos considerar OU uma OU outra.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 14,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros compõem o Conselho de Administração?",
        "Onde": ["7.3", "7.1"],
        "ComoPreencher": "CONTAR a quantidade de Conselheiros de Administração (EFETIVOS) incluido Presidente e Vice Presidente.",
        "OBSERVACOES": "A soma dos externos, independentes e executivos tem que ser igual ao número total de membros. NÃO CONTAR SUPLENTES.",
    },
    {
        "Nº": 15,
        "Dificuldade": "Médio",
        "Questao": "Quantas mulheres no Conselho de Administração?",
        "Onde": ["7.3", "7.1"],
        "ComoPreencher": "CONTAR a quantidade de mulheres no Conselho de Administração.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 16,
        "Dificuldade": "Médio",
        "Questao": "Quantos conselheiros são externos?",
        "Onde": ["7.3"],
        "ComoPreencher": "CONTAR a quantidade de Conselheiros que NÃO atuam como Diretores da companhia (EXECUTIVOS) e NÃO são Independentes.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 17,
        "Dificuldade": "Médio",
        "Questao": "Quantos conselheiros são independentes?",
        "Onde": ["7.3", "7.1"],
        "ComoPreencher": "CONTAR a quantidade de Conselheiros Independentes.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 18,
        "Dificuldade": "Médio",
        "Questao": "Quantos conselheiros são executivos da Empresa?",
        "Onde": ["7.3"],
        "ComoPreencher": "CONTAR a quantidade de Conselheiros Diretores na Empresa.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 19,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros compõem o Comitê de Auditoria?",
        "Onde": ["7.4"],
        "ComoPreencher": "CONTAR a quantidade de membros do Comitê de Auditoria.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 20,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros do Comitê de Auditoria são conselheiros?",
        "Onde": ["7.4", "7.3"],
        "ComoPreencher": "CONTAR a quantidade de membros do Comitê de Auditoria que também são do Conselho de Administração.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 21,
        "Dificuldade": "Médio",
        "Questao": "Quantos membros do Comitê de Auditoria são conselheiros independentes?",
        "Onde": ["7.4", "7.3"],
        "ComoPreencher": "CONTAR a quantidade de membros do Comitê de Auditoria que são conselheiros independentes.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 22,
        "Dificuldade": "Médio",
        "Questao": "O Comitê de Auditoria é coordenado por um conselheiro independente?",
        "Onde": ["7.4", "7.3"],
        "ComoPreencher": "SIM = O Coordenador do Comitê de Auditoria é Independente.",
        "OBSERVACOES": "",
    },
    {
        "Nº": 23,
        "Dificuldade": "Fácil",
        "Questao": "A empresa contrata seguro D&O para seus conselheiros e diretores, ou prevê outra forma de reembolso de despesas decorrentes de processos administrativos ou judiciais decorrentes do exercício de suas funções?",
        "Onde": ["7.7"],
        "ComoPreencher": "Seguro D&O = Afirma possuir D&O / SEGURO DE RESPONSABILIDADE CIVIL\nOutra forma de reembolso = Afirma possuir outra forma que não o D&O. \nNão = A empresa afirma Não possuir nenhum tipo de seguro ou reembolso\nNão divulgado = A empresa não disponibiliza essa informação",
        "OBSERVACOES": "Opções - Seguro D&O, Outras formas de reembolso, Não e Não Divulgado\nO seguro D&O (“Directors and Officers Liability Insurance”) é uma modalidade de seguro de responsabilidade civil.",
    },
    {
        "Nº": 24,
        "Dificuldade": "Médio",
        "Questao": "O emissor identificou casos de desvios, fraudes, irregularidades e atos ilícitos praticados contra a administração pública?",
        "Onde": ["5.3"],
        "ComoPreencher": "Sim= a empresa diz que identificou casos de desvios, fraudes, etc, nos últimos 3 exercícios sociais\nNão = a empresa diz que NÃO identificou casos de desvios, fraudes, etc, nos últimos 3 exercícios sociais\nNão Divulgado = A empresa não disponibiliza essa informação",
        "OBSERVACOES": "Analisar se a empresa, que incluiu risco de fraude no FR (item 4.1), teve algum caso confirmado",
    },
]
